import { ProjectIdea } from "../types";

/**
 * Provider-agnostic Markdown build spec for a generated project idea.
 * SECURITY: composed ONLY from idea-derived fields — never secrets, keys, or config.
 */
export function buildProjectSpecMarkdown(idea: ProjectIdea): string {
  const safe = (s?: unknown) => (typeof s === "string" ? s.trim() : "");
  const list = (arr?: string[]) =>
    Array.isArray(arr) && arr.length
      ? arr.map((x) => `- ${safe(x)}`).join("\n")
      : "_None specified._";

  const title = safe(idea.title) || "Untitled Project";
  const oneLiner = safe(idea.oneLiner);
  const desc = safe(idea.idea);
  const date = new Date().toISOString().slice(0, 10);

  const caps =
    Array.isArray(idea.capabilities) && idea.capabilities.length
      ? idea.capabilities
          .map((c) => {
            const name = safe(c?.name) || "Capability";
            const why = safe(c?.why);
            const url =
              typeof c?.docUrl === "string" && c.docUrl.startsWith("https://")
                ? ` ([docs](${c.docUrl}))`
                : "";
            return `- **${name}**${url} — ${why}`;
          })
          .join("\n")
      : "_None specified._";

  const milestones =
    Array.isArray(idea.milestones) && idea.milestones.length
      ? idea.milestones.map((m, i) => `${i + 1}. ${safe(m)}`).join("\n")
      : "_None specified._";

  return `# ${title}

${oneLiner ? `> ${oneLiner}\n` : ""}
## How to build this with any AI coding assistant

This is a **provider-agnostic build brief**. Hand this file to any coding agent —
Claude Code, Google AI Studio / Gemini, Cursor, GitHub Copilot, or a local model
via Ollama (e.g. \`llama3\`, \`hermes\`, \`mistral\`) — and ask it to implement the
project below. The recommended capabilities describe *what* the app needs; the
exact model or SDK is swappable per provider (see "Adapting to your provider").

> Treat this brief as a **starting point to review**, not commands to run blindly.
> It was generated from a short seed idea — verify each choice before building.

## Concept

${desc || "_No description provided._"}

## Recommended AI capabilities

${caps}

## Architecture blueprint

**Tech stack**
${list(idea.stack)}

**UI components**
${list(idea.uiComponents)}

**Infrastructure & compute**
${list(idea.infra)}

**Data flow**
${safe(idea.dataFlow) || "_Not specified._"}

## Milestones

${milestones}

## Risks & mitigations

${list(idea.risks)}

## First actionable step

${safe(idea.firstStep) || "_Not specified._"}

---

## Adapting to your provider

Keep every API key on a **server / backend** — never ship it in client code.
Swap only the model client; the rest of the architecture stays the same.

| Provider | Model client | Where the key lives |
| --- | --- | --- |
| Google (Gemini / AI Studio / Vertex) | \`@google/genai\` | Cloud Run + Secret Manager (server-side) |
| Anthropic Claude | \`@anthropic-ai/sdk\` | Server env var / secret store |
| OpenAI | \`openai\` | Server env var / secret store |
| Local (Ollama) | \`http://localhost:11434\` | No key — runs on your machine |

**Security baseline** (portable across all of the above):
- Authenticate users with a federated provider; verify the token on the server.
- Isolate each user's data by their verified user id — never trust a client-sent id.
- Validate and sanitize all inputs; treat model output as untrusted (escape before render).
- Never hardcode secrets; load them from a secret manager or environment.

---

_Generated by Journal Atelier · AI Project Studio${idea.modelUsed ? ` · ${safe(idea.modelUsed)}` : ""} · ${date}_
`;
}

export function slugify(s: string): string {
  const out = (s || "project")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
  return out || "project";
}

/**
 * Triggers a client-side .md download. Note: in a sandboxed iframe (AI Studio
 * preview) the click is silently ignored — always offer Copy as a fallback.
 */
export function downloadTextFile(filename: string, text: string): boolean {
  try {
    const blob = new Blob([text], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 1000);
    return true;
  } catch {
    return false;
  }
}

export async function copyText(text: string): Promise<boolean> {
  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(text);
      return true;
    }
  } catch {
    /* fall through to legacy path */
  }
  try {
    const ta = document.createElement("textarea");
    ta.value = text;
    ta.style.position = "fixed";
    ta.style.opacity = "0";
    document.body.appendChild(ta);
    ta.focus();
    ta.select();
    const ok = document.execCommand("copy");
    document.body.removeChild(ta);
    return ok;
  } catch {
    return false;
  }
}
